### ISSUE TITLE
/network/status returning incorrect block timestamp

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin-proxy#74]
We are seeing the network/status endpoint returning almost time.Now timestamp when it's still in `message sync` state. Do you mind looking into this since our health check depends on the timestamp we are getting to determine if the node is queryable

**Comment by raynaudoe** [comment]
When the node is syncing it actually returns `time.Now` since we cannot query chain's head timestamp during sync.

I can make the following change, if it works for you: 
- if node is syncing return **genesis** timestamp (which is always query-able regardless the sync state)
- if node is fully synced return **head** timestamp (current code)

**Comment by qiwu7** [comment]
Yeah this would work! Thank you so much for the quick response :)

**Comment by raynaudoe** [comment]
Great, I'll add the fix on #73
