### ISSUE TITLE
Inconsistency between Rosetta and Filfox - Investigate 

### ISSUE THREAD

**Issue by jleni** [Zondax/rosetta-filecoin-proxy#88]
As posted by @qiwu7 

> @jleni can we reopen this? The second issue I reported is not resolved.
> the transaction_identifier.hsh is inconsistent with block explorer. Not sure which one is correct and which is not. /block endpoint shows bafy2bzaceazqvy2eudmkvch4noyzqdj55k65phxsstbemitzisw7diqqjw324 whereas block explorer shows bafy2bzaceasogrhjxosqmdjyp6lcfhiu2eg24twfszhmvrslg7hesc3ozkrmi.

Based on https://github.com/Zondax/rosetta-filecoin-proxy/issues/77#issuecomment-707508058

**Comment by raynaudoe** [comment]
We should involve someone from Lotus to clarify if **_is there any difference between on getting the message's CID from_**:
(assuming that they both correspond to the same transaction)

CID1 from: **StateCompute**: `output.Trace[0].Msg.Cid().String()`
CID2 from: **ChainGetParentMessages**: `messages[0].Cid.String()`

**Comment by qiwu7** [comment]
Is CID1 the receipt CID and CID2 the original CID of the message?

**Comment by raynaudoe** [comment]
I guess not because `receipt` has its own field on the struct and I'm accessing to the (original?) message
https://github.com/filecoin-project/lotus/blob/1a70dbe37d1ec080a0b39f141bbd06a5cba89892/api/api_full.go#L738

**Comment by arajasek** [comment]
So this is because there are two message types: `Message` and `SignedMessage` that we often have to conflate when talking about messages. The difference is solely that `SignedMessage` includes a `signature` field.

The `ChainGetParentMessages` output is giving you the `SignedMessage` CID, which includes the siggy. This appears to be what filfox displays as well. The output from `StateCompute` is the unsigned message, which naturally has a different CID.

For internal consistency, I would recommend always using the unsigned message CID, which you can get from the `ChainGetParentMessages` output as `messages[0].Message.Cid()`. 

We _might_ wanna consider changing `ChainGetParentMessages` to return the unsigned message CID, but the larger problem of "urgh, we have 2 different ways (and so different CIDs) to think of a message" is...unfortunate.

**Comment by arajasek** [comment]
So this is because there are two message types: Message and SignedMessage that we often have to conflate when talking about messages. The difference is solely that SignedMessage includes a signature field.

The ChainGetParentMessages output is giving you the SignedMessage CID, which includes the siggy. This appears to be what filfox displays as well. The output from StateCompute is the unsigned message, which naturally has a different CID.

The "canonical" message CID is always the `SignedMessage` CID, but the VM doesn't see that (and so the `InvocResult` object is currently giving you the unsigned message CID). I can probably change the `InvocResult` struct a bit to have the canonical CID instead.

One minor point: This is only a difference observable in Secp messages. BLS messages are identical in their signed and unsigned versions (since the siggy gets aggregated with all other BLS siggys).

**Comment by qiwu7** [comment]
> The "canonical" message CID is always the SignedMessage CID, but the VM doesn't see that (and so the InvocResult object is currently giving you the unsigned message CID). I can probably change the InvocResult struct a bit to have the canonical CID instead.

Yeah it will be great if we are consistent here 👍
