### ISSUE TITLE
Run full rosetta reconciliation

### ISSUE THREAD

**Issue by jleni** [Zondax/rosetta-filecoin-proxy#92]
Move rosetta-cli tests to GitHub actions plus our own remote runner

**Comment by jleni** [comment]
Blocked until we get some fixes in rosetta-cli

**Comment by raynaudoe** [comment]
As mentioned in #97 , reconciliations percentage is about 99.93% on the tipset range `41281 - 41381` (same range used on the previous tests)

**Comment by raynaudoe** [comment]
According to last [test](https://github.com/Zondax/rosetta-filecoin-proxy/actions/runs/331253101) around 20k tipsets were synced with about `99.96%` reconciliation coverage. Test aborted due to a negative balance detected:
```
Error: unable to process blocks: unable to process block: negative balance -10000000000000000:&{Symbol:FIL Decimals:18 Metadata:map[]} for &{Address:f023016 SubAccount:<nil> Metadata:map[]} at &{Index:173542 Hash:0171a0e40220c18fdd47c0ccd7fe1961b74d55f85c4f1d7843d5ee9690fd58ee6d8f4af6ed1d}: unable to add block to storage 0171a0e40220c18fdd47c0ccd7fe1961b74d55f85c4f1d7843d5ee9690fd58ee6d8f4af6ed1d:173542:
```
Something is wrong with the account `f023016`. Very likely to be the same problem of `ActorID` vs `Robust` as msig accounts.

**Comment by jleni** [comment]
I think we can finally close this! We did run everything a few weeks ago!
